### ISSUE TITLE
Do you keep updating the code?

### ISSUE THREAD

**Issue by mbfreelanceweb** [Wolfcast/BrowserDetection#23]
Do you keep updating the code? Last released this on 28 Nov 2016... It's now the 2nd of May 2018! This kind of script is only useful if it is up to date! Thanks...

**Comment by Wolfcast** [comment]
Yes of course. I have a big update covering all the open ticket that is in the works since several months. It adds device type detection and I also refactored all regexp queries to cover some rare edge cases. But you are right I must take the time to finish that release ASAP! In my defense I think all major browsers are still covered 100% Only the newest MacOS release is missing so far...

**Comment by Wolfcast** [comment]
Sorry for the long delay but version 2.9.0 is out now! Will get minor updates out more often in the future while the bigger release are in the works.
