### ISSUE TITLE
_compatibilityViewVer 

### ISSUE THREAD

**Issue by syh** [Wolfcast/BrowserDetection#26]
When set my IE (actual version 11.0.9600.19180) in Compatibility Mode, 
The getIECompatibilityView() function returns always 7.0 as the  Emulation Version number, regardless what Document Mode I set on the F12 Developer Tools.

**Comment by Wolfcast** [comment]
I will check that in the next couple of days and report my findings (or issue a release if I fix something). Thanks for the report.

**Comment by Wolfcast** [comment]
When you change the Document Mode in IE11, the User Agent is not updated to reflect the current selected Document Mode. On the Emulation pane if you change the User agent string the class get the correct result because the UA is updated. I'm not sure why IE11 don't set the correct matching UA on a Document Mode change. Since IE11 is deprecated I doubt this will change.

**Comment by syh** [comment]
oh, i c . thank you very much
