### ISSUE TITLE
MacOS Sonoma detected as Catalina

### ISSUE THREAD

**Issue by djtechonline** [Wolfcast/BrowserDetection#36]
I noticed that the latest MacOS versions are not detected properly.  I tried adding the following to the macVerToStr() method to add MacOS Sonoma and Ventura, but I must have something wrong, as it still detects my OS (MacOS 14.4.1 - Sonoma) as Catalina:

```
if ($this->_platformVersion === '10') {
            return 'Mac OS X'; //Unspecified Mac OS X version
        } else if ($this->compareVersions($macVer, '14.0') >= 0 && $this->compareVersions($macVer, '15.0') < 0) {
            return 'macOS Sonoma';
        } else if ($this->compareVersions($macVer, '13.0') >= 0 && $this->compareVersions($macVer, '14.0') < 0) {
            return 'macOS Ventura';
         ...
```

**Comment by Wolfcast** [comment]
Can you provide your user agent so that I make sure the fix is OK?

**Comment by djtechonline** [comment]
Hi.  Sure!  I hope this helps.  This is what I got from https://whatmyuseragent.com: <https://whatmyuseragent.com/>


Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15

**Comment by Wolfcast** [comment]
A while ago, Safari froze the OS Version number in their user-agent string to "10_15_7" which breaks OS Version analysis in all web analytic tools. This means that if you are using Safari on Mac OS 11 or higher, your OS Version will always be reported as "10.15.7", regardless of what actual version you're running. Firefox and Chrome have followed suit, both reporting "10.15" and "10.15.7" respectively.

It's the same thing for Windows 11 being reported as 10 because browsers user-agent always report the OS as "Windows NT 10.0" when Windows >= 10.

They did all this for anti-tracking purposes and it's been like that for a couple of years now. I knew it for Windows but since I don't own/use Macs I wasn't aware. As you can see in your user-agent you have `Mac OS X 10_15_7` when you should have something like `Mac OS X 14_4_1`. Unfortunately there is not much to be done on the user-agent side :( I will release a new version later today with some notes in the comments around the place that were "frozen" by browsers vendors.

Some more info on the subject:
- https://stackoverflow.com/questions/70655946/how-to-detect-macos-big-sur-and-or-monterey-in-javascript
- https://medium.com/naver-fe-platform/prepare-for-client-hints-freezing-user-agent-9c0ea1ddd02c
- https://developers.google.com/privacy-sandbox/blog/user-agent-reduction-android-model-and-version
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent
